language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install libxml2-dev libcairo2-dev libpango1.0-dev ttf-lyx

install:
  - bundle install

cache: bundler

git:
  depth: 10
