language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

sudo: false

script:
  - script/cibuild

cache:
  - bundler
  - apt

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CFLAGS="$CFLAGS -DIS_TRAVISCI

git:
  depth: 10

addons:
  apt:
    packages:
    - cmake
    - bison
    - flex
    - libffi-dev
    - libxml2-dev
    - libgdk-pixbuf2.0-dev
    - libcairo2-dev
    - libpango1.0-dev
    - ttf-lyx
