language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2

sudo: false

script:
  - script/cibuild

cache:
  - bundler
  - apt

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

git:
  depth: 10

env:
  global:
    - CFLAGS="$CFLAGS -O0"

addons:
  apt:
    packages:
    - cmake
    - bison
    - flex
    - libffi-dev
    - libxml2-dev
    - libgdk-pixbuf2.0-dev
    - libcairo2-dev
    - libpango1.0-dev
    - ttf-lyx

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gdk-pixbuf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pango; fi
