name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - production

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-11.0
        ruby-version: [3.0.0, 2.7.2, 2.6.6, 2.5.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Linux packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run:
          - sudo apt-get update -qq
          - sudo apt-get install -y cmake bison flex libffi-dev libxml2-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev ttf-lyx

      - name: Install MacOS packages
        if: ${{ matrix.os == 'macos-11.0' }}
        run: sudo script/bootstrap

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: script/cibuild
